FROM odoo:19.0
# Custom addons are mounted via docker-compose (../addons -> /mnt/extra-addons).
# Add extra OS/python deps here if a module needs them, e.g.:
# USER root
# RUN pip3 install --no-cache-dir <pkg>
# USER odoo
