#!/usr/bin/env bash
#
# Point this clone's git hooks at the tracked .githooks/ directory.
#
# Run once per clone:
#     ./scripts/install_hooks.sh
#
# core.hooksPath is used rather than copying files into .git/hooks, so the hooks
# stay under version control and an update arrives with a `git pull` instead of
# needing every developer to re-copy. .git/hooks itself is never tracked, which
# is why an untracked hook silently rots.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

git config core.hooksPath .githooks
chmod +x .githooks/* 2>/dev/null || true

echo ">> core.hooksPath = $(git config --get core.hooksPath)"

if command -v gitleaks >/dev/null 2>&1; then
  echo ">> gitleaks found: $(gitleaks version)"
else
  cat >&2 <<'EOF'
!!
!! gitleaks is NOT installed. The hook is now active and will BLOCK every
!! commit until you install it — deliberately: a secret scanner that skips when
!! it is missing is a green light generated by doing nothing.
!!
!!   Windows (Git Bash):  winget install gitleaks
!!   macOS:               brew install gitleaks
!!   Linux:               https://github.com/gitleaks/gitleaks/releases
EOF
  exit 1
fi

cat <<'EOF'
>> Hooks installed.
>>
>> Now prove the guard actually fires — an untested guard is another thing that
>> passes by doing nothing:
>>
>>   printf '[options]\nadmin_passwd = %s\n' \
>>     "$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | cut -c1-32)" \
>>     > config/leaktest.conf
>>   git add -f config/leaktest.conf
>>   git commit -m 'should be blocked'      # must FAIL
>>   git reset config/leaktest.conf && rm config/leaktest.conf
EOF
