#!/usr/bin/env bash
# Provision a new client instance: create DB and install the base + chosen modules.
# Usage: ./scripts/provision_client.sh <db_name> [comma,separated,modules]
set -euo pipefail

DB_NAME="${1:?usage: provision_client.sh <db_name> [modules]}"
MODULES="${2:-sapian_core,l10n_et_payroll}"
COMPOSE="docker compose -f docker/docker-compose.yml"
ODOO_CONF="config/odoo.conf"

# --- Master password (admin_passwd) --------------------------------------------
# The database-manager master password protects DB create/drop/backup. It must
# be a strong, per-tenant secret and must NEVER be committed (A10). Generate one
# on first provisioning, write it into this tenant's runtime odoo.conf, and print
# it ONCE for the operator to store in the vault. Idempotent: an existing
# admin_passwd (a re-provision) is left untouched.
if grep -qE '^[[:space:]]*admin_passwd[[:space:]]*=' "${ODOO_CONF}"; then
  echo ">> admin_passwd already set in ${ODOO_CONF}; leaving it unchanged."
else
  ADMIN_PW="$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | cut -c1-32)"
  printf '\n; Per-tenant database master password (generated by provision_client.sh — do not commit).\nadmin_passwd = %s\n' \
    "${ADMIN_PW}" >> "${ODOO_CONF}"
  echo "============================================================"
  echo ">> Generated master password (admin_passwd) for this instance:"
  echo ">>     ${ADMIN_PW}"
  echo ">> Written to ${ODOO_CONF}. STORE IT IN YOUR VAULT NOW — shown once."
  echo "============================================================"
fi

echo ">> Provisioning client DB: ${DB_NAME}"
echo ">> Installing modules: ${MODULES}"

$COMPOSE run --rm odoo \
  odoo -d "${DB_NAME}" -i "${MODULES}" --without-demo=all --stop-after-init

echo ">> Done. Next: configure company/branding/roles via the onboarding wizard,"
echo ">>       import master data from data-templates/, enable backups & 2FA."
